plugins {
    id 'java'
    id 'pmd'
    id 'jacoco'
    id "io.freefair.lombok" version "6.5.1"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

group 'com.andrewpuglionesi'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

build.dependsOn check

dependencies {
    implementation 'org.apache.commons:commons-lang3:3.12.0'
    implementation 'com.google.guava:guava:31.1-jre'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    testImplementation 'net.datafaker:datafaker:1.6.0'
}

jacocoTestReport {
    doLast {
        project.logger.quiet("\nTests complete. View jacoco report at "
                + buildDir + "/reports/jacoco/test/html/index.html")
    }
}

test {
    maxHeapSize = "2g"
    useJUnitPlatform()
    finalizedBy {
        jacocoTestReport
    }
}

pmd {
    ruleSets = []
    ruleSetFiles(files("config/pmd/customruleset.xml"))
}